
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Slider } from '@/components/ui/slider';
import { Label } from '@/components/ui/label';
import { Download } from 'lucide-react';
import jsPDF from 'jspdf';

interface SaveReportFormProps {
  bmi: number;
  bmiCategory: string;
  height: number;
  weight: number;
  age: number;
  onSaveReport: (report: SavedReport) => void;
}

export interface SavedReport {
  id: string;
  name: string;
  description: string;
  bmi: number;
  bmiCategory: string;
  height: number;
  weight: number;
  age: number;
  notes: string;
  energyLevel: number;
  timestamp: Date;
}

const SaveReportForm = ({ bmi, bmiCategory, height, weight, age, onSaveReport }: SaveReportFormProps) => {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [notes, setNotes] = useState('');
  const [energyLevel, setEnergyLevel] = useState([5]);

  const getEnergyEmoji = (level: number) => {
    if (level <= 2) return '🥱';
    if (level <= 4) return '😐';
    if (level <= 6) return '🙂';
    if (level <= 8) return '😊';
    return '😄';
  };

  const getEnergyColor = (level: number) => {
    if (level <= 2) return 'from-gray-400 to-blue-400';
    if (level <= 4) return 'from-blue-400 to-yellow-400';
    if (level <= 6) return 'from-yellow-400 to-orange-400';
    if (level <= 8) return 'from-orange-400 to-green-400';
    return 'from-green-400 to-emerald-400';
  };

  const generatePDF = (report: SavedReport) => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(20);
    doc.setTextColor(40, 116, 166);
    doc.text('BMI Health Report', 20, 30);
    
    // Personal Information
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Name: ${report.name}`, 20, 50);
    doc.text(`Description: ${report.description}`, 20, 60);
    doc.text(`Date: ${report.timestamp.toLocaleDateString()}`, 20, 70);
    
    // BMI Results
    doc.setFontSize(16);
    doc.setTextColor(40, 116, 166);
    doc.text('BMI Results', 20, 90);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`BMI: ${report.bmi}`, 20, 105);
    doc.text(`Category: ${report.bmiCategory}`, 20, 115);
    doc.text(`Height: ${report.height} cm`, 20, 125);
    doc.text(`Weight: ${report.weight} kg`, 20, 135);
    doc.text(`Age: ${report.age} years`, 20, 145);
    doc.text(`Energy Level: ${report.energyLevel}/10`, 20, 155);
    
    // Notes
    if (report.notes) {
      doc.setFontSize(16);
      doc.setTextColor(40, 116, 166);
      doc.text('Notes', 20, 175);
      
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      const splitNotes = doc.splitTextToSize(report.notes, 170);
      doc.text(splitNotes, 20, 190);
    }
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by BMI Calculator App', 20, 280);
    
    // Save the PDF
    doc.save(`BMI_Report_${report.name}_${report.timestamp.toDateString()}.pdf`);
  };

  const handleSave = () => {
    if (!name.trim()) return;

    const report: SavedReport = {
      id: Date.now().toString(),
      name: name.trim(),
      description: description.trim(),
      bmi,
      bmiCategory,
      height,
      weight,
      age,
      notes: notes.trim(),
      energyLevel: energyLevel[0],
      timestamp: new Date()
    };

    onSaveReport(report);
    
    // Reset form
    setName('');
    setDescription('');
    setNotes('');
    setEnergyLevel([5]);
  };

  const handleSaveAsPDF = () => {
    if (!name.trim()) return;

    const report: SavedReport = {
      id: Date.now().toString(),
      name: name.trim(),
      description: description.trim(),
      bmi,
      bmiCategory,
      height,
      weight,
      age,
      notes: notes.trim(),
      energyLevel: energyLevel[0],
      timestamp: new Date()
    };

    generatePDF(report);
    onSaveReport(report);
    
    // Reset form
    setName('');
    setDescription('');
    setNotes('');
    setEnergyLevel([5]);
  };

  return (
    <div className="backdrop-blur-md bg-white/10 rounded-3xl p-8 border border-white/20 shadow-2xl">
      <h3 className="text-2xl font-bold mb-6 bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent text-center">
        Save Your Report
      </h3>
      
      <div className="space-y-6">
        {/* Name Input */}
        <div className="space-y-2">
          <Label htmlFor="name" className="text-cyan-300 font-semibold">Name</Label>
          <Input
            id="name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Enter your name"
            className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-cyan-400 focus:ring-cyan-400/20"
          />
        </div>

        {/* Description Input */}
        <div className="space-y-2">
          <Label htmlFor="description" className="text-cyan-300 font-semibold">Description</Label>
          <Input
            id="description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="e.g., Morning measurement, Post-workout check"
            className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-cyan-400 focus:ring-cyan-400/20"
          />
        </div>

        {/* Energy Level Slider */}
        <div className="space-y-4">
          <div className="flex justify-between items-center">
            <Label className="text-cyan-300 font-semibold">Energy Level</Label>
            <div className="flex items-center space-x-2">
              <span className="text-2xl">{getEnergyEmoji(energyLevel[0])}</span>
              <span className="text-xl font-bold bg-gradient-to-r from-cyan-400 to-purple-400 bg-clip-text text-transparent">
                {energyLevel[0]}/10
              </span>
            </div>
          </div>
          <div className="relative">
            <Slider
              value={energyLevel}
              onValueChange={setEnergyLevel}
              max={10}
              min={1}
              step={1}
              className="w-full"
            />
            <div className={`absolute -top-1 left-0 right-0 h-2 bg-gradient-to-r ${getEnergyColor(energyLevel[0])}/20 rounded-full -z-10`} />
          </div>
        </div>

        {/* Notes Textarea */}
        <div className="space-y-2">
          <Label htmlFor="notes" className="text-cyan-300 font-semibold">Notes</Label>
          <Textarea
            id="notes"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Add any additional notes about your health, diet, exercise, or how you're feeling today..."
            rows={4}
            className="bg-white/10 border-white/20 text-white placeholder:text-gray-400 focus:border-cyan-400 focus:ring-cyan-400/20 resize-none"
          />
        </div>

        {/* Action Buttons */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Button
            onClick={handleSave}
            disabled={!name.trim()}
            className="bg-gradient-to-r from-cyan-500 to-purple-600 hover:from-cyan-600 hover:to-purple-700 text-white font-semibold py-3 rounded-full text-lg shadow-lg shadow-purple-500/25 hover:shadow-purple-500/40 transition-all duration-300 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
          >
            Save Report
          </Button>
          
          <Button
            onClick={handleSaveAsPDF}
            disabled={!name.trim()}
            className="bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white font-semibold py-3 rounded-full text-lg shadow-lg shadow-emerald-500/25 hover:shadow-emerald-500/40 transition-all duration-300 hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 flex items-center gap-2"
          >
            <Download size={18} />
            Save as PDF
          </Button>
        </div>
      </div>
    </div>
  );
};

export default SaveReportForm;
